/*
 * ERROR CODE Head File 
 *   all error code are defined here, you may add 
 *   your error code here.
 *
 * Author: Leoanrdo Physh <leonardo.physh@yahoo.com.hk> 
 * Data : 2014.6.28
 */

#ifndef __ERROR_HEAD__
#define __ERROR_HEAD__

/*
 * Global error number 
 */
extern int err_num;
extern char *get_err_msg(int err);

/* error message */
#define DEFAUT_MSG  "未知错误，请联系厂商！"

/* RTC */
enum rtc {
	ERT=1,
	ERT_NUL_RT_OPS,
};

/* UI */
enum err_ui {
	EUI = 100,
	EUI_BACK,
	EUI_ESC,
	EUI_ENTER,
	EUI_TOTAL,
	EUI_HANG,
	EUI_VIEW,
	EUI_MODIFY,
	EUI_SHIFT,
	EUI_BAD_UI_ID,
	EUI_BAD_DATE_FORMAT,
	EUI_BAD_TIME_FORMAT,
};

/* Handler function */
enum err_func { 
	EFUNC=200,
	EFUNC_END_COVER_FAIL,
    EFUNC_FIRST_BOOT,
};

/* Display */
enum err_display {
	EDISPLAY = 300,
    ELCM_OPEN_FAIL,
    ELCM_IOCTL_FAIL,
    ELCM_WR_FAIL,
};

/* Printer */
enum err_print {
	EPRINT = 400,
	EPRINT_NODEV,    
	EPRINT_INIT,    	
	EPRINT_NOT_INIT,	
	EPRINT_NOCMD,    
	EPRINT_NOMOVEUNIT,    
	EPRINT_NOPAPER,       
	EPRINT_NOMEM,
	EPRINT_INITFAIL, 
	EPRINT_WR_ERR, 	
	EPRINT_RD_ERR,
    EPRINT_NO_PRINTER,    
};

/* TAX */
enum err_tax {
	ETAX = 500,
	ETAX_NOMEM, 		
	ETAX_NUL_RES_BUF,	
	ETAX_NUL_SEND_BUF, 	
	ETAX_BAD_CARD_TYPE,	
	ETAX_BAD_CMD_TYPE,	
	ETAX_BADAPDU,		
	ETAX_OPEN_CARD,		
	ETAX_WR_CARD,		
	ETAX_RD_CARD, 		
	ETAX_BAD_RES_HEAD, 	
	ETAX_BAD_CHKSUM, 	
	ETAX_WR_FILENAME, 	
	ETAX_BAD_SW, 		
	ETAX_BAD_COLLECT_TYPE,
	ETAX_UC_EMPTY,	
	ETAX_FC_PIN_LOCK,
	ETAX_CARD_PIN_LOCK,
	ETAX_NO_CARD_FILE,
	ETAX_MON_OUT_RANG,
	ETAX_BAD_XOR,
	ETAX_NUL_FISCAL_CARD,
	ETAX_NUL_USER_CARD,
    ETAX_NUL_CHECK_CARD,
	ETAX_CHK_CARD_DISMATCH,
    ETAX_CHK_CARD_PAST_DUE,
    ETAX_CHK_CARD_NOT_READY,
    ETAX_AUTH_CHKC_FAIL,
    ETAX_NEED_VF,
    ETAX_TAXPAYER_NB_NOT_MATCH,
	ETAX_NO_CARD_REC,    
	ETAX_UC_NOT_MATCH,  
	ETAX_DATE_CONFUSE,   
	ETAX_DIFF_MACH_NB,   
	ETAX_FC_HAS_REG,    
	ETAX_FC_NOT_READY,   
	ETAX_MACH_LOCKED, 	
	ETAX_FC_NOT_REG, 
	ETAX_INVOICE_FULL, 
	ETAX_UC_NOT_READY,
	ETAX_INVOICE_MC_EMPTY, 
	ETAX_NODATA_TO_DECLARE, 
	ETAX_BAD_DECLARE_TYPE, 	
	ETAX_UNKNOW_ERR,
	ETAX_ISSUE_LIMIT, 	
	ETAX_FISCAL_NOT_INIT, 
	ETAX_INVOICE_EMPTY, 	
	ETAX_INVOICE_NOT_MOUNT, 
	ETAX_AMT_TOTAL_LIMIT,
	ETAX_AMT_RETURN_LIMIT, 
	ETAX_USERNAME_IMPLICT,	
	ETAX_CARD_NOT_INIT,		
	ETAX_CARD_ERROR, 		
	ETAX_CARD_NOT_IN, 		
	ETAX_OUT_DECLARE_DATE,   
	ETAX_SPOIL_INV,          
	ETAX_RETURN_INV,         
	ETAX_INV_HAS_RETURNED,   
	ETAX_TAXPAYER_NAME_DISMATCH,	
};

/* FILE SYS */
enum err_file {
	EFILE = 600,
	EFILE_OPEN_FAIL, 
	EFILE_SEEK_FAIL, 
	EFILE_EOF, 		
	EFILE_RD_FAIL, 	
	EFILE_WR_FAIL, 	
	EFILE_OFFSET_OVER_FLOW, 
	EFILE_REC_HAS_DEL, 	
	EFILE_FULL_DEL_RECORD, 
	EFILE_DEL_UNAVAIL, 	
	EFILE_DEL_FAIL, 		
	EFILE_REC_FULL, 		
	EFILE_NO_REC,
};

/* Key board */
enum err_key {
	EKEY = 700,
	EKEY_NO_DATA, 	
	EKEY_ESC_CODE, 	
	EKEY_BACK_CODE, 	
	EKEY_ENTER_CODE, 
	EKEY_TOTAL_CODE, 
	EKEY_HANG, 	
	EKEY_VIEW, 	
	EKEY_MODIFY, 
	EKEY_SHIFT,	
};

/* PLU */
enum err_plu {
	EPLU = 800,
	EPLU_DPT_NOT_EMPTY, 
	EPLU_DPT_IS_FREE, 
	EPLU_DPT_IS_BUSY, 
	EPLU_NO_BARCODE, 
	EPLU_BARCODE_EXSIT,
	EPLU_DEL_BARCODE, 
	EPLU_NAME_EXSIT, 
	EPLU_DEL_NAME, 	
	EPLU_NO_NAME, 	
	EPLU_BAD_DPT_NUM,	
};

#endif /* __ERROR_HEAD__*/
